### ISSUE TITLE
Crash on 2.1.3

### ISSUE THREAD

**Issue by dalb8** [Ph1b/MaterialAudiobookPlayer#170]
After updating from 2.0.3 I get a crash on startup. OS is OmniROM 4.4.4 on a500.

```
I/ActivityManager(  395): Displayed de.ph1b.audiobook/.activity.BookActivity: +4s930ms
E/ACRA    (22461): ACRA is disabled for de.ph1b.audiobook - forwarding uncaught Exception on to default ExceptionHandler
E/AndroidRuntime(22461): FATAL EXCEPTION: main
E/AndroidRuntime(22461): Process: de.ph1b.audiobook, PID: 22461
E/AndroidRuntime(22461): java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{64a18148 position=3 id=3, oldPos=2, pLpos:2 scrap tmpDetached no parent}
E/AndroidRuntime(22461): 	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:3887)
E/AndroidRuntime(22461): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4018)
E/AndroidRuntime(22461): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3999)
E/AndroidRuntime(22461): 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1892)
E/AndroidRuntime(22461): 	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:419)
E/AndroidRuntime(22461): 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1301)
E/AndroidRuntime(22461): 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:534)
E/AndroidRuntime(22461): 	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:156)
E/AndroidRuntime(22461): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2365)
E/AndroidRuntime(22461): 	at android.support.v7.widget.RecyclerView.resumeRequestLayout(RecyclerView.java:1391)
E/AndroidRuntime(22461): 	at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:265)
E/AndroidRuntime(22461): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
E/AndroidRuntime(22461): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/AndroidRuntime(22461): 	at android.view.Choreographer.doFrame(Choreographer.java:543)
E/AndroidRuntime(22461): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
E/AndroidRuntime(22461): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(22461): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(22461): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(22461): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(22461): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22461): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(22461): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
W/ActivityManager(  395):   Force finishing activity de.ph1b.audiobook/.activity.BookActivity
W/ActivityManager(  395): Activity pause timeout for ActivityRecord{64918330 u0 de.ph1b.audiobook/.activity.BookActivity t31 f}
I/ActivityManager(  395): Killing 19467:com.android.deskclock/u0a29 (adj 15): empty #17
W/ActivityManager(  395): Activity destroy timeout for ActivityRecord{64918330 u0 de.ph1b.audiobook/.activity.BookActivity t31 f}
I/Process (22461): Sending signal. PID: 22461 SIG: 9
I/WindowState(  395): WIN DEATH: Window{64b90d78 u0 de.ph1b.audiobook/de.ph1b.audiobook.activity.BookActivity}
I/ActivityManager(  395): Process de.ph1b.audiobook (pid 22461) has died.
I/art     (19304): Heap trim of managed (duration=273us, advised=72KB) and native (duration=1.606ms, advised=4KB) heaps. Managed heap utilization of 42%.
```

**Comment by Ph1b** [comment]
Yeah, this is here for some versions now. I dont got how that happens, I think it has to do something with threading of adding and removing items from recycler.

**Comment by Ph1b** [comment]
Should be fixed as of [2.1.4](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/v2.1.4)

**Comment by floriangosse** [comment]
I have the same issue with version 2.5.0.8.

**Comment by floriangosse** [comment]
If I revoke the storage permissons and start the player again than I get the dialog which inform about the storage access and after this the permisson prompt. If I accept the permission request the app works. But if I stop the and try to restart the app it crashs again.
